# Generated by Django 5.1.2 on 2024-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pinglog',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
