# Generated by Django 5.1.2 on 2024-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_devicestatus_location_pinglog_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicestatus",
            name="version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pinglog",
            name="version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
