# Generated by Django 5.1.2 on 2025-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_devicestatus_version_pinglog_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicestatus",
            name="stream_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="devicestatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stream_id__isnull", False)),
                fields=("stream_id",),
                name="unique_stream_id",
            ),
        ),
    ]
