# Generated by Django 5.1.2 on 2024-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_devicestatus_version_pinglog_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicestatus",
            name="ffmpeg_pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicestatus",
            name="ffmpeg_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicestatus",
            name="stream_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
